# Generated by Django 4.2.2 on 2023-07-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='date',
            field=models.DateField(default='2000-04-16'),
            preserve_default=False,
        ),
    ]
